
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template

#con maven el properties cambia de lugar al igual que todo lo que no sea .java :)
hostname=ep-mute-bonus-aqocqyf1.c-8.us-east-1.aws.neon.tech
port=5432
database=mundial
username=neondb_owner
password=npg_rMfvibGhpk65